[versions]
agp = "8.3.0"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
compose-bom = "2024.02.00"
kotlinCoroutines = "1.7.3"
hilt = "2.48.1"
room = "2.6.1"
stripe = "23.0.0"
firebase-bom = "32.7.2"
maps-compose = "4.3.0"
maps-services = "18.1.0"
coil = "2.5.0"
vico = "1.12.0"
roborazzi = "1.3.0"
zxing = "4.3.0"
datastore = "1.0.0"
navigation = "2.7.6"
lifecycle = "2.7.0"
activity = "1.8.2"
window = "1.2.0"
biometric = "1.1.0"
play-services-location = "21.0.1"
play-services-auth = "20.7.0"
guava = "32.1.3-android"
work-runtime = "2.9.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
kotlin-serialization = "1.6.2"
multidex = "2.0.1"
firebase-permission = "17.0.0"
